server:
  port: 9000
  servlet:
    context-path: /ftp
logging:
  path: ${user.dir}/logs
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240MB
      max-request-size: 10240MB
